name: Auto_Build_Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        uses: actions/checkout@v2
      - run: |
          cd app/config && go test && cd ../../
          cd app/database && go test && cd ../../

      - name: Build
        uses: actions/checkout@v2
      - run: |
          go build